# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'hat-mobile-ios' do
    pod 'Alamofire'
    pod 'RealmSwift'
    pod 'SwiftyJSON'
    pod 'SwiftSpinner'
    pod 'FBAnnotationClusteringSwift'
    pod 'JLToast'

end

target 'hat-mobile-iosTests' do

end

target 'hat-mobile-iosUITests' do

end

