# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'hat-mobile-ios' do
    pod 'Alamofire'
    pod 'RealmSwift'
    pod 'SwiftyJSON'
    pod 'FBAnnotationClusteringSwift', git: 'https://github.com/ribl/FBAnnotationClusteringSwift/', branch: 'master'
    pod 'Toaster'
    pod 'JWTDecode'
    pod 'SwiftyRSA'
    pod 'KeychainSwift'
    pod 'PromiseKit'
end

target 'hat-mobile-iosTests' do

end

target 'hat-mobile-iosUITests' do

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
