# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!
# Uncomment this line if you're using Swift
use_frameworks!

target 'hat-mobile-ios' do
    pod 'Alamofire'
    pod 'RealmSwift'
    pod 'SwiftyJSON'
    pod 'FBAnnotationClusteringSwift', git: 'https://github.com/ribl/FBAnnotationClusteringSwift/', branch: 'master'
    pod 'Toaster'
    pod 'JWTDecode'
    pod 'SwiftyRSA'
    pod 'KeychainSwift'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'BEMCheckBox'
    pod 'zxcvbn-ios'
    pod 'HatForIOS', :git => 'https://github.com/whiteshadow-gr/HatForIOS.git'
    pod 'SwiftLint'
    
end

target 'hat-mobile-iosTests' do
    
    inherit! :complete
    pod 'Alamofire'
    pod 'RealmSwift'
    pod 'SwiftyJSON'
    pod 'FBAnnotationClusteringSwift', git: 'https://github.com/ribl/FBAnnotationClusteringSwift/', branch: 'master'
    pod 'Toaster'
    pod 'JWTDecode'
    pod 'SwiftyRSA'
    pod 'KeychainSwift'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'BEMCheckBox'
    pod 'HatForIOS', :git => 'https://github.com/whiteshadow-gr/HatForIOS.git'
    pod 'Mockingjay'
end

target 'hat-mobile-iosUITests' do

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
