/** Copyright (C) 2016 HAT Data Exchange Ltd
 * SPDX-License-Identifier: AGPL-3.0
 *
 * This file is part of the Hub of All Things project (HAT).
 *
 * RumpelLite is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation, version 3 of
 * the License.
 *
 * RumpelLite is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See
 * the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General
 * Public License along with this program. If not, see
 * <http://www.gnu.org/licenses/>.
 */

import UIKit

// MARK: Class

/// The Page view controller child. Shows info about hat and what you can do
class HATCapabilitiesViewController: UIViewController {
    
    // MARK: - Variables

    /// a variable to know the page number of the view
    var pageIndex: Int = 0
    
    // MARK: - IBOutlets
    
    /// An IBOutlet to handle the titleLabel
    @IBOutlet weak var titleLabel: UILabel!
    /// An IBOutlet to handle the imageView
    @IBOutlet weak var image: UIImageView!
    /// An IBOutlet to handle the infoLabel
    @IBOutlet weak var infoLabel: UILabel!
    
    // MARK: - Autogenerated methods
    
    override func viewDidLoad() {
        
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        
        // init the data object and refresh the labels and imageView
        let dataObject = LearnMoreObject(pageNumber: pageIndex + 10)
        titleLabel.text = dataObject.title
        infoLabel.text = dataObject.info
        image.image = dataObject.image
    }

    override func didReceiveMemoryWarning() {
        
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: - IBActions
    
    /**
     Hides the second page view controller
     
     - parameter sender: The object that calls this method
     */
    @IBAction func cancelButton(_ sender: Any) {
        
        NotificationCenter.default.post(name: Notification.Name("enablePageControll"), object: nil)
        NotificationCenter.default.post(name: Notification.Name("hidePageViewContoller"), object: nil)
    }
}
